//
// FC bus simulator "tuna"
//
#ifndef	__KAZZO_REQUEST_H__
#define	__KAZZO_REQUEST_H__

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	KAZZO_REQUEST_ECHO = 0,

	KAZZO_REQUEST_PHI2_INIT,
	KAZZO_REQUEST_CPU_READ_6502,
	KAZZO_REQUEST_CPU_READ, 
	KAZZO_REQUEST_CPU_WRITE_6502,
	KAZZO_REQUEST_CPU_WRITE_FLASH,
	KAZZO_REQUEST_PPU_READ,
	KAZZO_REQUEST_PPU_WRITE,
	KAZZO_REQUEST_FLASH_STATUS,
	KAZZO_REQUEST_FLASH_CONFIG_SET,
	KAZZO_REQUEST_FLASH_PROGRAM,
	KAZZO_REQUEST_FLASH_ERASE,
	KAZZO_REQUEST_FLASH_DEVICE,
	KAZZO_REQUEST_VRAM_CONNECTION,

	// future expanstion (not support)
	KAZZO_REQUEST_DISK_STATUS_GET,
	KAZZO_REQUEST_DISK_READ,
	KAZZO_REQUEST_DISK_WRITE,

	// bootloader control (not support)
	KAZZO_REQUEST_FIRMWARE_VERSION = 0x80,
	KAZZO_REQUEST_FIRMWARE_PROGRAM,
	KAZZO_REQUEST_FIRMWARE_DOWNLOAD,

	// internal use
	KAZZO_REQUEST_NOP = 0xEE
} KAZZO_REQUEST;

typedef enum {
	KAZZO_INDEX_IMPLIED = 0,
	KAZZO_INDEX_CPU,
	KAZZO_INDEX_PPU,
	KAZZO_INDEX_BOTH
} KAZZO_INDEX;

#define	KAZZO_VERSION_STRING_SIZE		0x20
#define	KAZZO_FLASH_PACKET_SIZE			0x0100

#ifdef __cplusplus
}
#endif

#endif
